server:
  servlet:
    context-path: /viabilizacion
  port: 5000

spring:
  datasource:
    url: jdbc:h2:mem:testdbCiudadController
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true