server:
  servlet:
    context-path: /viabilizacion
  port: 5000

servicios:
  uriValidarCiudad: http://localhost:5001/validacion/v1/ciudad/
  uriDictum: http://www.mocky.io/v2/5e3b08212f000063e356c899

